### ISSUE TITLE
NCMBを使用してのログイン・ログアウト機能の実装

### ISSUE THREAD

**Issue by kazuki-ccho** [ModerationLLC/smartlock-iOS12-#18]
以下の要件を押させつつログイン・ログアウトの実装を行う。

- 自動ログイン機能（一度ログインしたら、再度ログインIDパスワードを入力しない）
- 鍵をサーバから取得する際にmobileNoを入れていたと思います。mobileNoをログインしたIDにしてほしい。

**Comment by purinchann** [comment]
残タスク
・ログアウトボタン 位置
・mobile no 取得法

**Comment by purinchann** [comment]
ログイン画面が2回呼ばれる気持ち悪い動きを修正しました！
